# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1106, 593)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_writing = QtWidgets.QPushButton(self.centralwidget)
        self.start_writing.setGeometry(QtCore.QRect(10, 10, 85, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_writing.setFont(font)
        self.start_writing.setObjectName("start_writing")
        self.stop_writing = QtWidgets.QPushButton(self.centralwidget)
        self.stop_writing.setGeometry(QtCore.QRect(190, 10, 85, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_writing.setFont(font)
        self.stop_writing.setObjectName("stop_writing")
        self.current_fps = QtWidgets.QLabel(self.centralwidget)
        self.current_fps.setGeometry(QtCore.QRect(1020, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_fps.setFont(font)
        self.current_fps.setObjectName("current_fps")
        self.choose_out_folder = QtWidgets.QPushButton(self.centralwidget)
        self.choose_out_folder.setGeometry(QtCore.QRect(80, 290, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_out_folder.setFont(font)
        self.choose_out_folder.setObjectName("choose_out_folder")
        self.out_folder = QtWidgets.QLabel(self.centralwidget)
        self.out_folder.setGeometry(QtCore.QRect(10, 140, 281, 131))
        self.out_folder.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.out_folder.setFont(font)
        self.out_folder.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.out_folder.setObjectName("out_folder")
        self.video_view = QtWidgets.QLabel(self.centralwidget)
        self.video_view.setGeometry(QtCore.QRect(300, 40, 781, 431))
        self.video_view.setText("")
        self.video_view.setPixmap(QtGui.QPixmap("recoding_icon.gif"))
        self.video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.video_view.setObjectName("video_view")
        self.recording_state = QtWidgets.QLabel(self.centralwidget)
        self.recording_state.setGeometry(QtCore.QRect(300, 0, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.recording_state.setFont(font)
        self.recording_state.setObjectName("recording_state")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(960, 500, 141, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(960, 520, 141, 21))
        self.label_2.setObjectName("label_2")
        self.microphones = QtWidgets.QComboBox(self.centralwidget)
        self.microphones.setGeometry(QtCore.QRect(10, 90, 281, 22))
        self.microphones.setObjectName("microphones")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_writing.setText(_translate("MainWindow", "Запись"))
        self.stop_writing.setText(_translate("MainWindow", "Стоп"))
        self.current_fps.setText(_translate("MainWindow", "TextLabel"))
        self.choose_out_folder.setText(_translate("MainWindow", "Выбрать"))
        self.out_folder.setText(_translate("MainWindow", "Папка хранения видео"))
        self.recording_state.setText(_translate("MainWindow", "Запись идёт!"))
        self.label.setText(_translate("MainWindow", "Created with PyQt5"))
        self.label_2.setText(_translate("MainWindow", "Developer by Arsbul"))
        self.label_3.setText(_translate("MainWindow", "Аудиовход:"))
