# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_view = QtWidgets.QLabel(self.centralwidget)
        self.video_view.setGeometry(QtCore.QRect(0, 70, 781, 431))
        self.video_view.setText("")
        self.video_view.setPixmap(QtGui.QPixmap("monitor-1.png"))
        self.video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.video_view.setObjectName("video_view")
        self.start_writing = QtWidgets.QPushButton(self.centralwidget)
        self.start_writing.setGeometry(QtCore.QRect(920, 200, 85, 26))
        self.start_writing.setObjectName("start_writing")
        self.stop_writing = QtWidgets.QPushButton(self.centralwidget)
        self.stop_writing.setGeometry(QtCore.QRect(920, 350, 85, 26))
        self.stop_writing.setObjectName("stop_writing")
        self.current_fps = QtWidgets.QLabel(self.centralwidget)
        self.current_fps.setGeometry(QtCore.QRect(930, 80, 54, 14))
        self.current_fps.setObjectName("current_fps")
        self.choose_out_folder = QtWidgets.QPushButton(self.centralwidget)
        self.choose_out_folder.setGeometry(QtCore.QRect(810, 540, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_out_folder.setFont(font)
        self.choose_out_folder.setObjectName("choose_out_folder")
        self.out_folder = QtWidgets.QLabel(self.centralwidget)
        self.out_folder.setGeometry(QtCore.QRect(20, 540, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.out_folder.setFont(font)
        self.out_folder.setObjectName("out_folder")
        self.recording_icon = QtWidgets.QLabel(self.centralwidget)
        self.recording_icon.setGeometry(QtCore.QRect(30, 80, 121, 71))
        self.recording_icon.setObjectName("recording_icon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_writing.setText(_translate("MainWindow", "Запись"))
        self.stop_writing.setText(_translate("MainWindow", "Стоп"))
        self.current_fps.setText(_translate("MainWindow", "TextLabel"))
        self.choose_out_folder.setText(_translate("MainWindow", "Выбрать"))
        self.out_folder.setText(_translate("MainWindow", "Папка хранения видео"))
        self.recording_icon.setText(_translate("MainWindow", "TextLabel"))
